#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
# the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
#
# Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
# graphic logo is a trademark of OpenMRS Inc.
#

invoker.goals = clean verify
# openmrs.pgpverify.skip defaults to true, so we must set it to ensure this is run
# openmrs.pgpverify.failOnMissingSignature is turned off so we don't spuriously fail
#  the test just because an artefact wasn't signed. Here we only verify that the
#  plugin is run. The plugin's tests verify it works.
invoker.mavenOpts = -Dopenmrs.pgpverify.skip=false -Dopenmrs.pgpverify.failOnMissingSignature=false
invoker.buildResult = success
